server:
  port: 8090
  servlet:
    context-path: /business

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/business?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  level:
    root: info
    com.lx.quartz.mapper: debug